project:
  type: book
  output-dir: _book
  
book:
  title: "Interactive Statistics: Exploring Data with Shiny Applications"
  author: "JJB"
  description: | 
    Embark on a dynamic and engaging journey through the world of statistics
    with our innovative textbook, "Interactive Statistics: Exploring Data with Shiny Applications." 
    This book is designed to allow students to explore statistical ideas by 
    leveraging the power of Shiny applications.
  #cover-image: images/cover.png
  site-url: https://textbooks.thecoatlessprofessor.com/statistical-concepts-with-shiny-apps/
  repo-url: https://github.com/coatless-textbooks/statistical-concepts-with-shiny-apps/
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - part: my-first-book.qmd
      chapters: 
        - hello-world.qmd
  appendices:
    - appendix-notes.qmd
    
format:
  html:
    grid: 
      body-width: 1300px
    resources: 
      - shinylive-sw.js
    theme: cosmo
    code-link: true

# Enable the shinylive filter by default
filters:
  - shinylive